Mirantis/k8s-externalipcontroller

- .gitignore
- Dockerfile
- cmd/ipcontroller.go
- examples/externalipcontroller.yaml
- glide.lock
- glide.yaml
- pkg/controller.go
closes: https://github.com/Mirantis/k8s-externalipcontroller/issues/3
> Multiple fixes

- .travis.yml
- prepare.sh
closes: https://github.com/Mirantis/k8s-externalipcontroller/issues/11
> Add travis CI and necessary build scripts

- pkg/controller.go
- pkg/netutils/netutils.go
Cleanup of unused external IPs is introduced. When service is being deleted, corresponding IPs are being cleaned if no other service uses the same IPs.
> introduce IPs cleanup

- .dockerignore
- Dockerfile
- cmd/ipcontroller.go
- glide.lock
- glide.yaml
- pkg/controller.go
- pkg/ipmanager/fair.go
- prepare.sh
- run_tests.sh
- test/e2e/basic_test.go
- test/e2e/utils/utils.go
close: https://github.com/Mirantis/k8s-externalipcontroller/issues/33
close: https://github.com/Mirantis/k8s-externalipcontroller/issues/10
> Daemonset e2e

- .travis.yml
- Makefile
- prepare.sh
> Add Makefile with build and test targets

- Dockerfile
- Makefile
- test/e2e/basic_test.go
Use 'busybox' instead of 'debian' to reduce docker image size.
> Reduce image size

- .travis.yml
Push image into quay.io/l23network/k8s-externalipcontroller
Closes: https://github.com/Mirantis/k8s-externalipcontroller/issues/17
> Push image into hub.docker on successful build

- test/e2e/basic_test.go
closes: https://github.com/Mirantis/k8s-externalipcontroller/issues/80
> Implement e2e test case to cover assignment of same ips on all nodes

- .travis.yml
- glide.lock
- glide.yaml
- pkg/netutils/netutils.go
- test/e2e/basic_test.go
- test/integration/network_test.go
ARP announcement is done for every added address.
Closes: https://github.com/Mirantis/k8s-externalipcontroller/issues/13
> Arp announcement

- cmd/app/options.go
- cmd/app/scheduler.go
- examples/claims/scheduler.yaml
- glide.lock
- glide.yaml
- pkg/scheduler/scheduler.go
- test/e2e/basic_test.go
closes: https://github.com/Mirantis/k8s-externalipcontroller/issues/89
> Allow to run scheduler in leader election mode

- cmd/app/options.go
- cmd/app/scheduler.go
- examples/claims/scheduler.yaml
- glide.lock
- glide.yaml
- pkg/scheduler/scheduler.go
- test/e2e/basic_test.go
closes: https://github.com/Mirantis/k8s-externalipcontroller/issues/87
> Add some time for controllers to register themself after restart

- cmd/app/controller.go
- cmd/app/scheduler.go
- pkg/extensions/register.go
- test/e2e/basic_test.go
closes: https://github.com/Mirantis/k8s-externalipcontroller/issues/60
> Wait until TPRs will be registered

- cmd/app/controller.go
- cmd/app/options.go
- cmd/app/scheduler.go
- examples/claims/controller.yaml
- examples/claims/scheduler.yaml
- pkg/claimcontroller/controller.go
- pkg/scheduler/scheduler.go
Examples updated to show usage of those options
> Add options to tune latency for ip failover

- cmd/app/options.go
- cmd/app/scheduler.go
- cmd/ipmanager/main.go
- examples/claims/scheduler.yaml
- pkg/scheduler/node_filter.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- test/e2e/basic_test.go
> Add ability to select node filter using config options

- README.md
- doc/auto-allocation.md
- doc/operating-modes.md
- doc/simple-deployment-scheme.md
> Add docs on allpication modules and operating modes

- pkg/scheduler/scheduler.go
- pkg/workqueue/workqueue.go
Related: https://github.com/Mirantis/k8s-externalipcontroller/issues/9
> refactor auto allocation and fix messages

- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
Closes: https://github.com/Mirantis/k8s-externalipcontroller/issues/110
> Introduce queue to process IP claim change requests

- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- test/e2e/basic_test.go
Closes: https://github.com/Mirantis/k8s-externalipcontroller/issues/91
> Clean ipclaims

- Makefile
- scripts/config.sh
- scripts/dind.sh
- scripts/import.sh
- scripts/kube.sh
- scripts/push.sh
- fix syntax
- add dind compatible commit
> Fix syntax and add dind compatible commit

- doc/fail-over-optimization.md
- doc/operating-modes.md
Closes: https://github.com/Mirantis/k8s-externalipcontroller/issues/113
> add Fail-Over Optimization docs

- Makefile
Install missing dependencies for containerized-build
> Install missing dependencies for containerized-build

- README.md
- doc/deployment-examples.md
- doc/operating-modes.md
Related: https://github.com/Mirantis/k8s-externalipcontroller/issues/121
> add info regarding go version and fix spelling

- Makefile
- cmd/app/controller.go
- cmd/app/naive.go
- cmd/app/scheduler.go
- examples/claims/controller.yaml
- examples/claims/scheduler.yaml
- glide.lock
- glide.yaml
- pkg/claimcontroller/controller.go
- pkg/claimcontroller/controller_test.go
- pkg/controller.go
- pkg/controller_test.go
- pkg/extensions/client.go
- pkg/extensions/register.go
- pkg/extensions/testing/client.go
- pkg/extensions/types.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- test/e2e/basic_test.go
- test/e2e/utils/utils.go
- test/integration/network_test.go
closes: https://github.com/Mirantis/k8s-externalipcontroller/issues/133
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-externalipcontroller/134)
> Support k8s 1.8

- pkg/scheduler/scheduler.go
Apparently garbage collector started to work for custom resource
definitions. ipcontroller logic needs to take it into account
when ipclaims are managed.
For now i will make a reference to non existing type so that
garbage collector will continue to ignore ipclaim objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mirantis/k8s-externalipcontroller/139)
> Add a workaround for kubernetes garbage collector
